name: MirrorChyan Release Note
description: MirrorChyan Release Note
author: MirrorChyan

branding:
  icon: arrow-up
  color: black

inputs:
  version_name:
    required: false
  release_note:
    required: false

  auto_channel:
    required: false
    default: "true"
  channel:
    required: false

  mirrorchyan_rid:
    required: true
  upload_token:
    required: true
  github_token:
    required: false
  owner:
    required: false
  repo:
    required: false

outputs:
  error:
    value: ${{ steps.upload.outputs.error }}
  msg:
    value: ${{ steps.upload.outputs.msg }}
  response:
    value: ${{ steps.upload.outputs.response }}

runs:
  using: "composite"
  steps:
    - id: latest-release
      if: ${{ inputs.version_name == '' || inputs.release_note == '' }}
      uses: MirrorChyan/github-action-get-latest-release@master
      with:
        owner: ${{ inputs.owner || github.repository_owner }}
        repo: ${{ inputs.repo || github.event.repository.name }}
        token: ${{ inputs.github_token }}
        tag: ${{ inputs.version_name }}
        excludes: "draft"

    - name: Organize information
      id: information
      shell: bash
      env:
        version_name: ${{ inputs.version_name == '' && steps.latest-release.outputs.release || inputs.version_name }}
        release_note: ${{ inputs.release_note == '' && steps.latest-release.outputs.description || inputs.release_note }}
      run: |
        if [[ "${{ inputs.channel }}" == "" ]]; then
          if [[ "$version_name" == *"alpha"* ]]; then
            channel="alpha"
          elif [[ "$version_name" == *"beta"* ]]; then
            channel="beta"
          elif [[ "$version_name" == *"rc"* ]]; then
            channel="beta"
          else
            channel="stable"
          fi
        else
          channel="${{ inputs.channel }}"
        fi
        
        jq -cn --arg version_name "$version_name" --arg channel "$channel" --arg content "$release_note" '$ARGS.named' > body.json
        
        artifact="MirrorChyan-${{ inputs.mirrorchyan_rid }}-$version_name-release_note"
        artifact="${artifact//:/_}"
        artifact="${artifact// /+}"
        echo "artifact=$artifact" | tee -a "$GITHUB_OUTPUT"

    - name: Upload to MirrorChyan
      id: upload
      shell: bash
      run: |
        cat body.json

        if [ ! -f "mirrorchyan_release_note.py" ];then
          wget -O mirrorchyan_release_note.py https://raw.githubusercontent.com/MirrorChyan/release-note-action/refs/heads/v1/python/upload.py
          python -m pip install aiohttp asyncio
        fi

        python mirrorchyan_release_note.py '${{ inputs.mirrorchyan_rid }}' '${{ inputs.upload_token }}' body.json

    - name: Create issue if failed
      if: failure()
      uses: actions-cool/issues-helper@v3
      with:
        actions: "create-issue"
        title: "Failed to upload release note to MirrorChyan for ${{ github.repository }}"
        body: |
          ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

          @MistEO @Aliothmoon @dongwlin

    - name: Notify admin if failed
      if: failure()
      shell: bash
      run: |
          curl -L -X POST 'https://dev.mirrorchyan.com/api/misc/notify_admin?dev=1' \
            --header 'Content-Type: application/json' \
            --header 'Authorization: ${{ inputs.upload_token }}' \
            --data '{"rid":"${{ inputs.mirrorchyan_rid }}", "url":"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}", "module":"ReleaseNote"}' 

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ steps.information.outputs.artifact }}
        path: body.json
