name: MirrorChyan Release Note
description: MirrorChyan Release Note
author: MirrorChyan

branding:
  icon: arrow-up
  color: black

inputs:
  version_name:
    required: false
  release_note:
    required: false

  auto_channel:
    required: false
    default: "true"
  channel:
    required: false

  mirrorchyan_rid:
    required: true
  upload_token:
    required: true
  github_token:
    required: false
  owner:
    required: false
  repo:
    required: false

outputs:
  error:
    value: ${{ steps.upload.outputs.error }}
  msg:
    value: ${{ steps.upload.outputs.msg }}
  response:
    value: ${{ steps.upload.outputs.response }}

runs:
  using: "composite"
  steps:
    - id: latest-release
      if: ${{ inputs.version_name == '' }}
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        owner: ${{ inputs.owner || github.repository_owner }}
        repo: ${{ inputs.repo || github.event.repository.name }}
        token: ${{ inputs.github_token }}

    - name: Organize information
      id: information
      shell: bash
      env:
        version_name: ${{ inputs.version_name == '' && steps.latest-release.outputs.release || inputs.version_name }}
        release_note: ${{ inputs.version_name == '' && steps.latest-release.outputs.description || inputs.release_note }}
      run: |
        if [[ "${{ inputs.channel }}" == "" ]]; then
          if [[ "$version_name" == *"alpha"* ]]; then
            channel="alpha"
          elif [[ "$version_name" == *"beta"* ]]; then
            channel="beta"
          elif [[ "$version_name" == *"rc"* ]]; then
            channel="beta"
          else
            channel="stable"
          fi
        else
          channel="${{ inputs.channel }}"
        fi
        
        jq -cn --arg version_name "$version_name" --arg channel "$channel" --arg content "$release_note" '$ARGS.named' > body.json

    - name: Upload to MirrorChyan
      id: upload
      shell: bash
      run: |
        cat body.json

        if [ ! -f "mirrorchyan_release_note.py" ];then
          wget -O mirrorchyan_release_note.py https://raw.githubusercontent.com/MirrorChyan/release-note-action/refs/heads/v1/python/upload.py
          python -m pip install requests
        fi

        python mirrorchyan_release_note.py '${{ inputs.mirrorchyan_rid }}' '${{ inputs.upload_token }}' body.json
