name: demo1 for MAA

on:
  workflow_dispatch:
  push:

jobs:
  release_note:
    runs-on: macos-latest
    steps:
      - name: Upload MAA release note for demo1
        uses: MirrorChyan/release-note-action@v1
        with:
          mirrorchyan_rid: demo1

          owner: MaaAssistantArknights
          repo: MaaAssistantArknights

          upload_token: ${{ secrets.MirrorChyanUploadTokenForDemo1 }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
